import uuid
from datetime import datetime, timezone
from typing import Optional

from sqlmodel import SQLModel, Field


class Invite(SQLModel, table=True):
    """An invite link generated by an official (HYPER) member.

    Anyone with the token can join as an unofficial member via
    `POST /members/join`. Joiners receive access for `access_duration_seconds`
    starting from the moment they join.
    """

    id: uuid.UUID = Field(primary_key=True, default_factory=uuid.uuid4)
    token: str = Field(unique=True, index=True)
    created_by: uuid.UUID = Field(foreign_key="user.id")
    # How long a joining member can access Invoicely, in seconds.
    access_duration_seconds: int
    # Visibility group assigned to anyone who joins via this invite:
    # hyper | unofficial | private (see User.group).
    group: str = Field(default="unofficial")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    use_count: int = Field(default=0)
