import { sqliteTable, text, integer, uniqueIndex, index } from "drizzle-orm/sqlite-core";

/**
 * D1 (SQLite) schema for Invoicely.
 *
 * Ported from the legacy SQLModel definitions. SQLite-specific adjustments:
 *  - UUIDs stored as TEXT (v4 strings). The frontend already treats ids as strings.
 *  - Money stored as INTEGER cents to avoid floating-point drift (was Decimal(12,2)).
 *  - Timestamps stored as TEXT ISO-8601 UTC (sortable, comparable).
 *  - Booleans stored as INTEGER 0/1.
 *
 * Migrations are generated by `drizzle-kit generate` into ../migrations and
 * applied with `wrangler d1 migrations apply`. Keep this file and the SQL
 * migrations in sync.
 */

// ── Users ────────────────────────────────────────────────────────────────────

export const users = sqliteTable(
  "users",
  {
    id: text("id").primaryKey(), // uuid v4 string
    name: text("name").notNull(),
    email: text("email").notNull(),
    // HYPER (Arcademia) linkage. A user with a hyper_id is "official" (admin):
    // permanent access, the only ones who can manage other members.
    hyperId: text("hyper_id"),
    accountType: text("account_type"),

    // Access control for unofficial (invite-joined) members.
    // access_expires_at = NULL means permanent. is_kicked = ban.
    // Officials always have access regardless of these fields.
    accessExpiresAt: text("access_expires_at"), // ISO-8601 UTC or NULL
    isKicked: integer("is_kicked", { mode: "boolean" }).notNull().default(false),
    // Local scrypt hash for unofficial members. Officials never set this.
    passwordHash: text("password_hash"),
    // Visibility group for unofficial members, controls which bills they see:
    //  hyper | unofficial | private. Officials always see every bill.
    group: text("group").notNull().default("unofficial"),

    createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  },
  (t) => [
    uniqueIndex("users_email_idx").on(t.email),
    uniqueIndex("users_hyper_id_idx").on(t.hyperId),
  ],
);

// ── Bills ────────────────────────────────────────────────────────────────────

export const bills = sqliteTable(
  "bills",
  {
    id: text("id").primaryKey(),
    title: text("title").notNull(),
    description: text("description").notNull().default(""),
    status: text("status").notNull().default("open"), // open | settled
    // Total cost of the bill in integer cents (sum of expenses). Stored so the
    // bill carries an explicit total independent of client-side math.
    totalCostCents: integer("total_cost_cents").notNull().default(0),
    createdBy: text("created_by"), // -> users.id (NULL allowed)
    createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
    updatedAt: text("updated_at").notNull().$defaultFn(() => new Date().toISOString()),
  },
  (t) => [index("bills_created_by_idx").on(t.createdBy), index("bills_created_at_idx").on(t.createdAt)],
);

export const billMembers = sqliteTable(
  "bill_members",
  {
    id: text("id").primaryKey(),
    billId: text("bill_id").notNull(),
    userId: text("user_id").notNull(),
    // How much this member has paid toward their share, in integer cents.
    // 0 = nothing paid yet. Derived `paid` = paidCents >= share; owes = share - paidCents.
    paidCents: integer("paid_cents").notNull().default(0),
  },
  (t) => [index("bill_members_bill_idx").on(t.billId), index("bill_members_user_idx").on(t.userId)],
);

export const expenses = sqliteTable(
  "expenses",
  {
    id: text("id").primaryKey(),
    description: text("description").notNull(),
    // Stored as integer cents to avoid float drift. (was Decimal(12,2))
    amountCents: integer("amount_cents").notNull(),
    createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),

    billId: text("bill_id").notNull(),
    paidByMemberId: text("paid_by_member_id").notNull(), // -> bill_members.id
    paidByUserId: text("paid_by_user_id").notNull(), // -> users.id
  },
  (t) => [
    index("expenses_bill_idx").on(t.billId),
    index("expenses_paid_by_user_idx").on(t.paidByUserId),
  ],
);

// ── Notifications ─────────────────────────────────────────────────────────────

export const notifications = sqliteTable(
  "notifications",
  {
    id: text("id").primaryKey(),
    // bill_added | bill_settled | member_joined | payment_received
    type: text("type").notNull(),
    title: text("title").notNull(),
    description: text("description").notNull().default(""),
    billId: text("bill_id"), // -> bills.id, nullable
    // Per-recipient scoping. Users only ever see their own rows.
    userId: text("user_id"), // -> users.id (NULL = legacy orphan)
    read: integer("read", { mode: "boolean" }).notNull().default(false),
    createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  },
  (t) => [index("notifications_user_idx").on(t.userId), index("notifications_bill_idx").on(t.billId)],
);

// ── Invites ──────────────────────────────────────────────────────────────────

export const invites = sqliteTable(
  "invites",
  {
    id: text("id").primaryKey(),
    token: text("token").notNull(),
    createdBy: text("created_by").notNull(), // -> users.id
    accessDurationSeconds: integer("access_duration_seconds").notNull(),
    group: text("group").notNull().default("unofficial"), // hyper | unofficial | private
    createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
    useCount: integer("use_count").notNull().default(0),
    // When the link itself expires (distinct from the access it grants). NULL = never.
    expiresAt: text("expires_at"),
    // Max joins allowed. NULL = unlimited.
    maxUses: integer("max_uses"),
  },
  (t) => [uniqueIndex("invites_token_idx").on(t.token)],
);

// ── Sessions ─────────────────────────────────────────────────────────────────

export const sessions = sqliteTable(
  "sessions",
  {
    token: text("token").primaryKey(), // opaque backend-issued session token
    userId: text("user_id").notNull(), // -> users.id
    createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  },
  (t) => [index("sessions_user_idx").on(t.userId)],
);

// ── User settings ─────────────────────────────────────────────────────────────

export const userSettings = sqliteTable("user_settings", {
  userId: text("user_id").primaryKey(), // -> users.id
  defaultCurrency: text("default_currency").notNull().default("NPR"),
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Bill = typeof bills.$inferSelect;
export type BillMember = typeof billMembers.$inferSelect;
export type Expense = typeof expenses.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
export type Invite = typeof invites.$inferSelect;
export type Session = typeof sessions.$inferSelect;
export type UserSetting = typeof userSettings.$inferSelect;
