"""add status and timestamps

Revision ID: baebb5e7ca8c
Revises: 187295b79bae
Create Date: 2026-06-11 18:16:20.091577

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baebb5e7ca8c'
down_revision: Union[str, Sequence[str], None] = '187295b79bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('bill', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='open'))
    op.add_column('bill', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('bill', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('expense', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'created_at')
    op.drop_column('bill', 'updated_at')
    op.drop_column('bill', 'created_at')
    op.drop_column('bill', 'status')
    # ### end Alembic commands ###
